#!/bin/bash
echo "Enter your age "
read age
if [ $age -lt 13 ]
then
echo "CHILD"
elif [ $age -ge 13 -a $age -le 19 ]
then
echo "TEEN"
elif [ $age -ge 20 -a $age -le 59 ]
then
echo "ADULT"
else
echo "OLDAGE"
fi
